# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ekstraklasa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Team',
            new_name='UserTeam',
        ),
        migrations.RemoveField(
            model_name='players',
            name='user',
        ),
    ]
