# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekstraklasa', '0003_auto_20180409_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='activities',
            field=models.ManyToManyField(null=True, related_name='player_activity', to='Ekstraklasa.Activities', verbose_name='Punktowanie czynności'),
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(1, 'Bramkarz'), (2, 'Obrońca'), (3, 'Pomocnik'), (4, 'Napastnik')], null=True, verbose_name='Pozycja'),
        ),
    ]
