# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekstraklasa', '0004_auto_20180409_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='is_specific',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='players',
            name='last_game_points',
            field=models.IntegerField(null=True, verbose_name='Punkty w ostatniej kolejce'),
        ),
        migrations.AlterField(
            model_name='players',
            name='overall_points',
            field=models.IntegerField(null=True, verbose_name='Suma punktów'),
        ),
    ]
