# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekstraklasa', '0005_auto_20180409_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameweek',
            name='matches',
        ),
        migrations.AlterModelOptions(
            name='userteam',
            options={'verbose_name': 'Kolejka', 'verbose_name_plural': 'Kolejki'},
        ),
        migrations.RemoveField(
            model_name='activities',
            name='player',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='gameweek',
        ),
        migrations.AddField(
            model_name='activities',
            name='point_value',
            field=models.IntegerField(default=0, verbose_name='Wartość punktowa'),
        ),
        migrations.AlterField(
            model_name='players',
            name='is_specific',
            field=models.NullBooleanField(default=False, verbose_name='Czy jest "specificzny"?'),
        ),
        migrations.DeleteModel(
            name='Gameweek',
        ),
    ]
