# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ekstraklasa', '0006_auto_20180420_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userteam',
            options={'verbose_name': 'Zespół użytkownika', 'verbose_name_plural': 'Zespoły użytkowników'},
        ),
    ]
