# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekstraklasa', '0008_userteam_team_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballmatch',
            name='date_time',
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='date',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='time',
            field=models.TimeField(null=True, verbose_name='Godzina'),
        ),
    ]
