# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekstraklasa', '0009_auto_20180421_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='position',
            field=models.IntegerField(choices=[(1, 'Bramkarz'), (2, 'Obrońca'), (3, 'Pomocnik'), (4, 'Napastnik'), (5, 'Wszyscy')], null=True, verbose_name='dot_pozycji'),
        ),
    ]
