# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ekstraklasa', '0012_remove_players_last_game_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='match',
        ),
    ]
