# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekstraklasa', '0013_remove_activities_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballmatch',
            name='away_red_cards',
            field=models.IntegerField(default=0, verbose_name='Ilość czerwonych kartek gości'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_substitutes',
            field=models.IntegerField(default=0, verbose_name='Ilość zmian gości'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_team_assists',
            field=models.IntegerField(default=0, verbose_name='Ilość asyst gości'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Ilość żółtych kartek gości'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_red_cards',
            field=models.IntegerField(default=0, verbose_name='Ilość czerwonych kartek gospodarzy'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_substitutes',
            field=models.IntegerField(default=0, verbose_name='Ilość zmian gospodarzy'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_team_assists',
            field=models.IntegerField(default=0, verbose_name='Ilość goli gości'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Ilość żółtych kartek gospodarzy'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='away_team_goals',
            field=models.IntegerField(default=0, verbose_name='Gole Gości'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='away_team_players',
            field=models.ManyToManyField(default=0, related_name='played_as_guest', to='Ekstraklasa.Players', verbose_name='Zawodnicy Gości'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='home_team_goals',
            field=models.IntegerField(default=0, verbose_name='Gole gospodarzy'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='home_team_players',
            field=models.ManyToManyField(default=0, related_name='played_as_host', to='Ekstraklasa.Players', verbose_name='Zawodnicy Gospodarzy'),
        ),
    ]
