# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ekstraklasa', '0015_remove_activities_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballmatch',
            name='away_red_cards',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='away_substitutes',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='away_team_assists',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='away_yellow_cards',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='home_red_cards',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='home_substitutes',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='home_team_assists',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='home_yellow_cards',
        ),
    ]
