# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ekstraklasa', '0016_auto_20180422_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['position'], 'verbose_name': 'Zawodnik', 'verbose_name_plural': 'Zawodnicy'},
        ),
    ]
